version: '3'

services:
    workspace:
        image: happywork/workspace:latest
        build:
            context: ../src/workspace
        working_dir: /var/www
        volumes:
            - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
        tty: true
        restart: always
        networks:
            - frontend
            - backend
    php-fpm:
        image: happywork/php-fpm:latest
        build:
            context: ../src/php-fpm
            args:
                - INSTALL_XDEBUG=${PHP_FPM_INSTALL_XDEBUG}
                - INSTALL_ZIP_ARCHIVE=${PHP_FPM_INSTALL_ZIP_ARCHIVE}
                - INSTALL_PHPREDIS=${PHP_FPM_INSTALL_PHPREDIS}
                - INSTALL_OPCACHE=${PHP_FPM_INSTALL_OPCACHE}
                - INSTALL_EXIF=${PHP_FPM_INSTALL_EXIF}
                - INSTALL_MYSQLI=${PHP_FPM_INSTALL_MYSQLI}
                - INSTALL_GD=${PHP_FPM_INSTALL_GD}
                - INSTALL_MCRYPT=${PHP_FPM_INSTALL_MCRYPT}
        volumes:
            - ../src/php-fpm/php.ini:/usr/local/etc/php/php.ini
            - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
        restart: always
        networks:
            - backend
    php-worker:
        image: happywork/php-worker:latest
        build:
            context: ../src/php-worker
            args:
                - INSTALL_ZIP_ARCHIVE=${PHP_FPM_INSTALL_ZIP_ARCHIVE}
                - INSTALL_PHPREDIS=${PHP_FPM_INSTALL_PHPREDIS}
                - INSTALL_OPCACHE=${PHP_FPM_INSTALL_OPCACHE}
                - INSTALL_EXIF=${PHP_FPM_INSTALL_EXIF}
                - INSTALL_MYSQLI=${PHP_FPM_INSTALL_MYSQLI}
                - INSTALL_GD=${PHP_FPM_INSTALL_GD}
                - INSTALL_MCRYPT=${PHP_FPM_INSTALL_MCRYPT}
        volumes:
            - ../src/php-worker/supervisord.d:/etc/supervisord.d
            - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
        restart: always
        networks:
            - backend
    nginx:
        image: happywork/nginx:latest
        build:
            context: ../src/nginx
        volumes:
            - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
            - ../src/nginx/sites:/etc/nginx/sites-available
        restart: always
        ports:
            - '${NGINX_HOST_HTTP_PORT}:80'
            - '${NGINX_HOST_HTTPS_PORT}:443'
        depends_on:
            - php-fpm
        networks:
            - frontend
            - backend
    mysql:
        image: mariadb:latest
        environment:
            MYSQL_DATABASE: happywork
            MYSQL_MAJOR: '5.7'
            MYSQL_PASSWORD: '123456'
            MYSQL_ROOT_PASSWORD: '123456'
            MYSQL_USER: happywork
        restart: always
        ports:
            - '3306:3306'
        volumes:
            - ${DATA_PATH_HOST}/mysql:/var/lib/mysql
        networks:
            - backend
    redis:
        image: redis:latest
        command:
            - '--appendonly'
            - 'yes'
            - '--requirepass'
            - '123456'
        restart: always
        volumes:
            - '${DATA_PATH_HOST}/redis:/data:rw'
        networks:
            - backend
networks:
    frontend:
        driver: 'bridge'
    backend:
        driver: 'bridge'
